# Generated by Django 4.1.1 on 2022-09-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='accounts.board'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
