# Generated by Django 4.1.1 on 2022-09-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_topic_board_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
